## dirs
data_dir: "/home/pervinco/Datasets/BKAI_IGH_NeoPolyp"
save_dir: "./runs"
train: "train_sub"
valid: "valid_sub"
test: "test"
pretrain_weight: "" #"/home/pervinco/TransResUNet/checkpoint-BKAI-IGH.pth"
test_weight: ""

## backbone
backbone: "resnet152"
num_layers: 2 ## encoder layers

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

## hyp-params
epochs: 500
img_size: 256
batch_size: 32
initial_lr: 0.0001
betas: [0.9, 0.999]
momentum: 0.9
weight_decay: 0.05 ## default 0.01

## Loss func
num_classes: 3
crossentropy: True

## lr scheduler
scheduler: "decay"
max_lr: 0.001
pct_start: 0.8

## early-stop
early_stopping_patience: 50

## pred samples
num_pred_samples: 5
